# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: Awesome PowerShell Daily Markdown Link Verification

on:
  workflow_dispatch:
  schedule:
  # At 13:00 UTC every day.
  - cron:  '0 13 * * *'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check Links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: .github/workflows/markdown-link/config.json
